version: '3.8'
services:
  mock-oneiss:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:cached
      - vendor:/var/www/html/vendor
    restart: unless-stopped
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1

volumes:
  vendor:
    driver: local
